version: 1.3.6.{build}
image: Visual Studio 2017
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore

build:
  project: NLog.Targets.Sentry.sln
  parallel: true
  verbosity: minimal

test:
  assemblies:
    - '**\*.UnitTests.dll'
